name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-24.04-arm
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-14
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}

      - name: Install musl tools
        if: matrix.target == 'x86_64-unknown-linux-musl' || matrix.target == 'aarch64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build
        run: |
          if [ "${{ matrix.target }}" = "x86_64-unknown-linux-musl" ] || [ "${{ matrix.target }}" = "aarch64-unknown-linux-musl" ]; then
            export CC=musl-gcc
          fi
          cargo build --release --target ${{ matrix.target }}

      - name: Create archive
        shell: bash
        run: |
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            ARCHIVE_FILE="ghost_${{ matrix.target }}.zip"
            7z a "$ARCHIVE_FILE" "./target/${{ matrix.target }}/release/ghost.exe"
          else
            ARCHIVE_FILE="ghost_${{ matrix.target }}.tar.gz"
            tar -czf "$ARCHIVE_FILE" -C "./target/${{ matrix.target }}/release" ghost
          fi
          echo "ARCHIVE_FILE=$ARCHIVE_FILE" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghost_${{ matrix.target }}
          path: ${{ env.ARCHIVE_FILE }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/*/*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
